server:
  port: 8001
spring:
  application:
    name: SINHVIENSERVICE
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sinhviendb
    username: sa
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888