server:
  port: 8081
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=userdb
    username: sa
    password: sapassword
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
    application:
      name: USERSERVICE
