server:
  port: 8000
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=facultydb
    username: sa
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  application:
    name: FACULTYSERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888